### ISSUE TITLE
Synthetic blurring

### ISSUE THREAD

**Issue by sieme97** [Abdullah-Abuolaim/recurrent-defocus-deblurring-synth-dual-pixel#1]
Hi,
Thank you for interesting paper. 
Can you provide the code for applying psf? Also, how long did it take to generate a single dp pair.

**Comment by Abdullah-Abuolaim** [comment]
Hello there,

Thanks for your interest in this work.
All the codes including the one of applying PSF will be released at once. We expect this to be soon.

Regarding the second question, we are able to generate a dp pair in less than 4s on Intel Core i7-6700 CPU.

Best,
Abdullah
