### ISSUE TITLE
cut off factor parameter(alpha in paper)

### ISSUE THREAD

**Issue by wcy199705** [Abdullah-Abuolaim/recurrent-defocus-deblurring-synth-dual-pixel#3]
Hello
Thank you for your contributions.
I want to make a synthetic DP dataset using your code.
Unlike your ICCV2021 paper, in the code, I can not find the alpha which is a parameter for the cut-off frequency(D0) of the Butterworth filter.
In the code, 'cut_off_factor' parameters are {2.5, 2} unlike the paper (alpha={0.4,0.6,0.8,1.0}).
Could you tell me how to make the 'cut_off_factor' with the alpha parameter in the paper?

Thank you!

**Comment by Abdullah-Abuolaim** [comment]
Hello there,

Thanks for pointing this out.
The 'cut_off_factor' parameter is equal to 1/alpha in the code. So, all you need is just to 'cut_off_factor' to {2.5, 1.67, 1.25, 1}.

Best,
Abdullah
