### ISSUE TITLE
the test phase,there are a file lost,"vid_test_samples_list.npy",can you release it?

### ISSUE THREAD

**Issue by jucaizhai** [Abdullah-Abuolaim/recurrent-defocus-deblurring-synth-dual-pixel#4]
the test phase,there are a file lost,"vid_test_samples_list.npy",can you release it?

**Comment by Abdullah-Abuolaim** [comment]
Thanks for your question.
It is a randomly generated test set of an arbitrary number of the starting frames.
You can generate it yourself or try a list I generated by replacing **line 152** in the `rdpd_code/data.py` file with the following:
first_frame_list=[15, 39, 93, 127, 116, 23, 94, 163, 178, 104]
